import { Platform } from "./platformTypes";

// ─── HYPOTHESIS TYPE ──────────────────────────────────────────────────────────

export interface HuntHypothesis {
  id: string;
  title: string;
  hypothesis: string;
  tactic: string;
  techniqueId: string;
  techniqueName: string;
  attackUrl: string;
  priority: "CRITICAL" | "HIGH" | "MEDIUM";
  dataSources: string[];
  falsePositiveRisk: "LOW" | "MEDIUM" | "HIGH";
  queryHints: Record<Platform, string>; // short natural language hint per platform
}

// ─── 40 HUNT HYPOTHESES ───────────────────────────────────────────────────────

export const HUNT_HYPOTHESES: HuntHypothesis[] = [

  // ── EXECUTION ───────────────────────────────────────────────────────────────
  {
    id: "H001",
    title: "PowerShell Encoded Command Execution",
    hypothesis: "I hypothesize that an adversary is using PowerShell with encoded commands to evade command-line logging and execute malicious payloads, observable as Base64-encoded -EncodedCommand arguments in process telemetry.",
    tactic: "Execution",
    techniqueId: "T1059.001",
    techniqueName: "PowerShell",
    attackUrl: "https://attack.mitre.org/techniques/T1059/001/",
    priority: "HIGH",
    dataSources: ["Process Events", "Command Line Logging"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "PowerShell processes with -EncodedCommand or -enc in command line, last 24 hours",
      kql: "DeviceProcessEvents where powershell.exe has EncodedCommand in ProcessCommandLine",
      spl: "Sysmon EventCode=1 powershell.exe with EncodedCommand in CommandLine",
      cql: "ProcessRollup2 FileName powershell.exe with EncodedCommand in CommandLine",
    },
  },
  {
    id: "H002",
    title: "Office Application Spawning Shell Interpreter",
    hypothesis: "I hypothesize that a malicious document is being used to execute code by spawning command interpreters from Office applications, observable as cmd.exe, PowerShell, or scripting engines with Office apps as parent process.",
    tactic: "Execution",
    techniqueId: "T1566.001",
    techniqueName: "Spearphishing Attachment",
    attackUrl: "https://attack.mitre.org/techniques/T1566/001/",
    priority: "CRITICAL",
    dataSources: ["Process Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "cmd.exe or powershell.exe spawned by winword.exe, excel.exe, or outlook.exe",
      kql: "DeviceProcessEvents InitiatingProcessFileName in Office apps, FileName in shells",
      spl: "Sysmon EventCode=1 ParentImage Office apps Image shells",
      cql: "ProcessRollup2 ParentBaseFileName Office apps FileName shell interpreters",
    },
  },
  {
    id: "H003",
    title: "MSHTA Remote Script Execution",
    hypothesis: "I hypothesize that an adversary is using mshta.exe to execute remote HTA scripts, bypassing application whitelisting, observable as mshta.exe with HTTP/HTTPS URLs or UNC paths in its command line.",
    tactic: "Defense Evasion",
    techniqueId: "T1218.005",
    techniqueName: "Mshta",
    attackUrl: "https://attack.mitre.org/techniques/T1218/005/",
    priority: "HIGH",
    dataSources: ["Process Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "mshta.exe processes with http or UNC paths in command line",
      kql: "DeviceProcessEvents FileName mshta.exe with http in ProcessCommandLine",
      spl: "Sysmon EventCode=1 Image mshta.exe CommandLine http",
      cql: "ProcessRollup2 FileName mshta.exe CommandLine http",
    },
  },
  {
    id: "H004",
    title: "Certutil Payload Download or Decode",
    hypothesis: "I hypothesize that an adversary is abusing certutil.exe to download files from the internet or decode Base64-encoded payloads, observable as certutil with -urlcache, -decode, or -encode arguments.",
    tactic: "Defense Evasion",
    techniqueId: "T1140",
    techniqueName: "Deobfuscate/Decode Files or Information",
    attackUrl: "https://attack.mitre.org/techniques/T1140/",
    priority: "HIGH",
    dataSources: ["Process Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "certutil.exe with -urlcache, -decode, or -encode in command line",
      kql: "DeviceProcessEvents FileName certutil.exe with urlcache or decode in command line",
      spl: "Sysmon EventCode=1 Image certutil.exe CommandLine urlcache OR decode",
      cql: "ProcessRollup2 FileName certutil.exe CommandLine urlcache OR decode",
    },
  },
  {
    id: "H005",
    title: "Regsvr32 Squiblydoo — Remote DLL Load",
    hypothesis: "I hypothesize that an adversary is using regsvr32.exe to load a COM scriptlet from a remote URL, bypassing application control, observable as regsvr32 with /s /u /i: flags and HTTP URLs.",
    tactic: "Defense Evasion",
    techniqueId: "T1218.010",
    techniqueName: "Regsvr32",
    attackUrl: "https://attack.mitre.org/techniques/T1218/010/",
    priority: "HIGH",
    dataSources: ["Process Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "regsvr32.exe with http or UNC path and /i: or /u flags in command line",
      kql: "DeviceProcessEvents FileName regsvr32.exe with http in ProcessCommandLine",
      spl: "Sysmon EventCode=1 Image regsvr32.exe CommandLine http",
      cql: "ProcessRollup2 FileName regsvr32.exe CommandLine http",
    },
  },

  // ── CREDENTIAL ACCESS ────────────────────────────────────────────────────────
  {
    id: "H006",
    title: "LSASS Memory Dumping",
    hypothesis: "I hypothesize that an adversary is accessing LSASS memory to extract credentials, observable as non-system processes opening a handle to lsass.exe, or use of procdump/comsvcs MiniDump against LSASS.",
    tactic: "Credential Access",
    techniqueId: "T1003.001",
    techniqueName: "LSASS Memory",
    attackUrl: "https://attack.mitre.org/techniques/T1003/001/",
    priority: "CRITICAL",
    dataSources: ["Process Events", "API Call Telemetry"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "Non-system processes accessing lsass.exe or procdump targeting lsass",
      kql: "DeviceEvents OpenProcessApiCall targeting lsass.exe from unexpected processes",
      spl: "Sysmon EventCode=10 TargetImage lsass.exe SourceImage not system processes",
      cql: "ProcessRollup2 TargetProcessName lsass not MsMpEng or werfault",
    },
  },
  {
    id: "H007",
    title: "Kerberoasting — SPN Enumeration",
    hypothesis: "I hypothesize that an adversary is performing Kerberoasting by requesting Kerberos service tickets for service accounts, observable as unusual LDAP queries for servicePrincipalName attributes from workstations.",
    tactic: "Credential Access",
    techniqueId: "T1558.003",
    techniqueName: "Kerberoasting",
    attackUrl: "https://attack.mitre.org/techniques/T1558/003/",
    priority: "HIGH",
    dataSources: ["Directory Service Logs", "Network Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "LDAP queries for servicePrincipalName from non-DC hosts, last 7 days",
      kql: "IdentityDirectoryEvents LDAP queries for SPN attributes",
      spl: "Windows Security EventCode=4769 TicketEncryptionType=0x17 not service accounts",
      cql: "AuthActivityAuditEvent Kerberos TGS requests with RC4 encryption",
    },
  },
  {
    id: "H008",
    title: "DCSync — Unauthorized AD Replication",
    hypothesis: "I hypothesize that an adversary is using DCSync to extract password hashes from Active Directory by impersonating a domain controller replication request, observable as DS-Replication-Get-Changes permissions from non-DC hosts.",
    tactic: "Credential Access",
    techniqueId: "T1003.006",
    techniqueName: "DCSync",
    attackUrl: "https://attack.mitre.org/techniques/T1003/006/",
    priority: "CRITICAL",
    dataSources: ["Directory Service Logs", "Security Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "AD replication requests EventCode 4662 from non-DC hosts accessing replication attributes",
      kql: "IdentityDirectoryEvents replication requests from non-domain-controller devices",
      spl: "Windows Security EventCode=4662 ObjectType DS-Replication from non-DC hosts",
      cql: "AuthActivityAuditEvent replication DS-Replication-Get-Changes non-DC source",
    },
  },
  {
    id: "H009",
    title: "SAM Database Access",
    hypothesis: "I hypothesize that an adversary is attempting to read the SAM database to extract local account hashes, observable as reg.exe or other processes accessing HKLM\\SAM outside of system context.",
    tactic: "Credential Access",
    techniqueId: "T1003.002",
    techniqueName: "Security Account Manager",
    attackUrl: "https://attack.mitre.org/techniques/T1003/002/",
    priority: "HIGH",
    dataSources: ["Registry Events", "Process Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "Registry access to HKLM\\SAM by non-SYSTEM processes",
      kql: "DeviceRegistryEvents RegistryKey contains SAM from non-system processes",
      spl: "Sysmon EventCode=12 OR EventCode=13 TargetObject HKLM\\SAM non-system",
      cql: "RegKeyValueSetByProcessId RegistryPath SAM FileName not system processes",
    },
  },
  {
    id: "H010",
    title: "Credential Harvesting via Password Store Access",
    hypothesis: "I hypothesize that an adversary is extracting saved credentials from browser password stores or Windows Credential Manager, observable as unusual process access to credential vault files or APIs.",
    tactic: "Credential Access",
    techniqueId: "T1555",
    techniqueName: "Credentials from Password Stores",
    attackUrl: "https://attack.mitre.org/techniques/T1555/",
    priority: "HIGH",
    dataSources: ["File Events", "Process Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "Processes accessing browser Login Data files or Windows Credential Manager outside of browser",
      kql: "DeviceFileEvents file access to Login Data or vault files by non-browser processes",
      spl: "Sysmon EventCode=11 TargetFilename Login Data OR vault non-browser process",
      cql: "NewExecutableWritten OR ProcessRollup2 accessing credential store paths",
    },
  },

  // ── LATERAL MOVEMENT ─────────────────────────────────────────────────────────
  {
    id: "H011",
    title: "Pass-the-Hash Lateral Movement",
    hypothesis: "I hypothesize that an adversary is using stolen NTLM hashes to authenticate laterally across the network without knowing plaintext passwords, observable as NTLM type 3 authentications from workstations with mismatched hostnames.",
    tactic: "Lateral Movement",
    techniqueId: "T1550.002",
    techniqueName: "Pass the Hash",
    attackUrl: "https://attack.mitre.org/techniques/T1550/002/",
    priority: "CRITICAL",
    dataSources: ["Authentication Events", "Network Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "NTLM authentication events with source hostname not matching source IP",
      kql: "IdentityLogonEvents NTLM authentication from workstations to servers",
      spl: "Windows Security EventCode=4624 LogonType=3 AuthenticationPackageName=NTLM unexpected",
      cql: "UserLogon LogonType=3 NTLM from unexpected source hosts",
    },
  },
  {
    id: "H012",
    title: "PsExec or Remote Execution Tool Usage",
    hypothesis: "I hypothesize that an adversary is using PsExec or similar remote execution tools to move laterally, observable as PSEXESVC service creation, admin share connections, or characteristic named pipe activity.",
    tactic: "Lateral Movement",
    techniqueId: "T1570",
    techniqueName: "Lateral Tool Transfer",
    attackUrl: "https://attack.mitre.org/techniques/T1570/",
    priority: "HIGH",
    dataSources: ["Process Events", "Service Events", "Network Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "PSEXESVC service creation or psexec.exe execution across multiple hosts",
      kql: "DeviceProcessEvents or DeviceEvents PsExec service creation or named pipe",
      spl: "EventCode=7045 ServiceName PSEXESVC OR Sysmon EventCode=17 psexec pipe",
      cql: "ProcessRollup2 FileName psexec OR RegKeyCreated PSEXESVC service",
    },
  },
  {
    id: "H013",
    title: "RDP Lateral Movement — Workstation to Workstation",
    hypothesis: "I hypothesize that an adversary is using RDP for lateral movement between workstations, observable as RDP connections originating from workstations rather than jump servers or IT admin systems.",
    tactic: "Lateral Movement",
    techniqueId: "T1021.001",
    techniqueName: "Remote Desktop Protocol",
    attackUrl: "https://attack.mitre.org/techniques/T1021/001/",
    priority: "HIGH",
    dataSources: ["Network Events", "Authentication Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "Network connections on port 3389 originating from workstations to other workstations",
      kql: "DeviceNetworkEvents RemotePort 3389 from non-server devices to non-server devices",
      spl: "Network traffic dest_port=3389 from workstation IP ranges to workstation IP ranges",
      cql: "NetworkConnectIP4 RemotePort=3389 from non-admin workstations",
    },
  },
  {
    id: "H014",
    title: "WMI Lateral Movement",
    hypothesis: "I hypothesize that an adversary is using WMI to execute commands on remote systems, observable as WmiPrvSE.exe spawning child processes or Win32_Process Create calls from unusual sources.",
    tactic: "Lateral Movement",
    techniqueId: "T1021.006",
    techniqueName: "Windows Remote Management",
    attackUrl: "https://attack.mitre.org/techniques/T1021/006/",
    priority: "HIGH",
    dataSources: ["Process Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "WmiPrvSE.exe spawning shell or scripting processes across multiple hosts",
      kql: "DeviceProcessEvents InitiatingProcessFileName WmiPrvSE.exe spawning shells",
      spl: "Sysmon EventCode=1 ParentImage WmiPrvSE.exe Image cmd or powershell",
      cql: "ProcessRollup2 ParentBaseFileName WmiPrvSE.exe FileName shell interpreters",
    },
  },
  {
    id: "H015",
    title: "SMB Admin Share Lateral Movement",
    hypothesis: "I hypothesize that an adversary is accessing administrative shares (C$, ADMIN$, IPC$) for lateral movement or file staging, observable as unusual net use commands or SMB connections to admin shares from non-IT systems.",
    tactic: "Lateral Movement",
    techniqueId: "T1021.002",
    techniqueName: "SMB/Windows Admin Shares",
    attackUrl: "https://attack.mitre.org/techniques/T1021/002/",
    priority: "HIGH",
    dataSources: ["Network Events", "Process Events"],
    falsePositiveRisk: "HIGH",
    queryHints: {
      xql: "Network connections on port 445 from workstations to multiple other hosts",
      kql: "DeviceNetworkEvents RemotePort 445 from non-server devices to multiple destinations",
      spl: "Network traffic dest_port=445 from workstations high connection count",
      cql: "NetworkConnectIP4 RemotePort=445 from workstations to multiple destinations",
    },
  },

  // ── PERSISTENCE ───────────────────────────────────────────────────────────────
  {
    id: "H016",
    title: "Registry Run Key Persistence",
    hypothesis: "I hypothesize that an adversary has established persistence by adding entries to Windows Run or RunOnce registry keys, observable as non-installer processes writing to HKLM/HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run.",
    tactic: "Persistence",
    techniqueId: "T1547.001",
    techniqueName: "Registry Run Keys / Startup Folder",
    attackUrl: "https://attack.mitre.org/techniques/T1547/001/",
    priority: "HIGH",
    dataSources: ["Registry Events"],
    falsePositiveRisk: "HIGH",
    queryHints: {
      xql: "Registry writes to Run or RunOnce keys by non-installer processes, last 7 days",
      kql: "DeviceRegistryEvents RegistryKey contains CurrentVersion\\Run by non-installers",
      spl: "Sysmon EventCode=13 TargetObject CurrentVersion\\Run non-installer processes",
      cql: "RegKeyValueSetByProcessId RegistryPath CurrentVersion\\Run unexpected process",
    },
  },
  {
    id: "H017",
    title: "Scheduled Task Persistence",
    hypothesis: "I hypothesize that an adversary created a scheduled task for persistence, observable as schtasks.exe /create commands, new XML task files in C:\\Windows\\System32\\Tasks, or EventID 4698 outside of maintenance windows.",
    tactic: "Persistence",
    techniqueId: "T1053.005",
    techniqueName: "Scheduled Task",
    attackUrl: "https://attack.mitre.org/techniques/T1053/005/",
    priority: "HIGH",
    dataSources: ["Process Events", "File Events", "Security Events"],
    falsePositiveRisk: "HIGH",
    queryHints: {
      xql: "schtasks.exe /create commands or new task files in Windows Tasks directory",
      kql: "DeviceProcessEvents schtasks.exe with create flag or DeviceFileEvents Tasks directory",
      spl: "Sysmon EventCode=1 Image schtasks.exe CommandLine /create OR EventCode=4698",
      cql: "ProcessRollup2 FileName schtasks.exe CommandLine /create",
    },
  },
  {
    id: "H018",
    title: "New Windows Service Installation",
    hypothesis: "I hypothesize that an adversary installed a malicious Windows service for persistence or execution, observable as sc.exe create commands, new service registry keys, or EventID 7045 outside of known patch or deployment windows.",
    tactic: "Persistence",
    techniqueId: "T1543.003",
    techniqueName: "Windows Service",
    attackUrl: "https://attack.mitre.org/techniques/T1543/003/",
    priority: "HIGH",
    dataSources: ["Security Events", "Registry Events"],
    falsePositiveRisk: "HIGH",
    queryHints: {
      xql: "sc.exe create commands or new service registry entries outside business hours",
      kql: "DeviceRegistryEvents or DeviceEvents service creation EventCode 7045",
      spl: "EventCode=7045 new service installation outside maintenance window",
      cql: "ProcessRollup2 FileName sc.exe CommandLine create OR RegKeyCreated services",
    },
  },
  {
    id: "H019",
    title: "WMI Event Subscription Persistence",
    hypothesis: "I hypothesize that an adversary created a WMI event subscription for fileless persistence, observable as new WMI EventFilter, EventConsumer, or FilterToConsumerBinding objects being created.",
    tactic: "Persistence",
    techniqueId: "T1546.003",
    techniqueName: "Windows Management Instrumentation Event Subscription",
    attackUrl: "https://attack.mitre.org/techniques/T1546/003/",
    priority: "HIGH",
    dataSources: ["WMI Events", "Process Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "WMI EventFilter or EventConsumer creation by non-system processes",
      kql: "DeviceEvents WMI subscription creation or mofcomp.exe execution",
      spl: "Sysmon EventCode=19 OR EventCode=20 OR EventCode=21 WMI subscription",
      cql: "ProcessRollup2 FileName mofcomp.exe OR WMI subscription event creation",
    },
  },
  {
    id: "H020",
    title: "BITS Job Persistence",
    hypothesis: "I hypothesize that an adversary is using Background Intelligent Transfer Service (BITS) for persistence or C2 communication, observable as bitsadmin.exe or PowerShell BITS cmdlets creating unusual transfer jobs.",
    tactic: "Persistence",
    techniqueId: "T1197",
    techniqueName: "BITS Jobs",
    attackUrl: "https://attack.mitre.org/techniques/T1197/",
    priority: "MEDIUM",
    dataSources: ["Process Events", "Network Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "bitsadmin.exe with /transfer or /addfile flags or BITS PowerShell cmdlets",
      kql: "DeviceProcessEvents bitsadmin.exe or Start-BitsTransfer with external URLs",
      spl: "Sysmon EventCode=1 Image bitsadmin.exe OR CommandLine Start-BitsTransfer",
      cql: "ProcessRollup2 FileName bitsadmin.exe CommandLine transfer OR addfile",
    },
  },

  // ── DEFENSE EVASION ───────────────────────────────────────────────────────────
  {
    id: "H021",
    title: "Process Injection via Unusual Parent-Child",
    hypothesis: "I hypothesize that an adversary is injecting code into legitimate processes to evade detection, observable as unusual parent-child process relationships where high-integrity processes spawn from low-privilege parents.",
    tactic: "Defense Evasion",
    techniqueId: "T1055",
    techniqueName: "Process Injection",
    attackUrl: "https://attack.mitre.org/techniques/T1055/",
    priority: "HIGH",
    dataSources: ["Process Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "Processes with unexpected parent relationships, high integrity spawned from user context",
      kql: "DeviceProcessEvents unusual InitiatingProcessFileName for system process children",
      spl: "Sysmon EventCode=1 unexpected parent-child process combinations",
      cql: "ProcessRollup2 unexpected ParentBaseFileName for system processes",
    },
  },
  {
    id: "H022",
    title: "Obfuscated Command Lines — High Entropy",
    hypothesis: "I hypothesize that an adversary is using command-line obfuscation to evade detection, observable as processes with unusually long command lines, high character entropy, or excessive use of escape characters and concatenation.",
    tactic: "Defense Evasion",
    techniqueId: "T1027",
    techniqueName: "Obfuscated Files or Information",
    attackUrl: "https://attack.mitre.org/techniques/T1027/",
    priority: "HIGH",
    dataSources: ["Process Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "PowerShell or cmd processes with command lines longer than 500 characters",
      kql: "DeviceProcessEvents strlen ProcessCommandLine over 500 for shell processes",
      spl: "Sysmon EventCode=1 len(CommandLine) > 500 shell interpreters",
      cql: "ProcessRollup2 FileName powershell.exe long CommandLine length",
    },
  },
  {
    id: "H023",
    title: "Shadow Copy Deletion — Ransomware Precursor",
    hypothesis: "I hypothesize that an adversary is preparing for ransomware deployment by deleting Volume Shadow Copies to prevent recovery, observable as vssadmin.exe delete or wmic shadowcopy delete commands.",
    tactic: "Impact",
    techniqueId: "T1490",
    techniqueName: "Inhibit System Recovery",
    attackUrl: "https://attack.mitre.org/techniques/T1490/",
    priority: "CRITICAL",
    dataSources: ["Process Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "vssadmin.exe delete shadows or wmic shadowcopy delete commands",
      kql: "DeviceProcessEvents vssadmin.exe or wmic.exe with shadow copy deletion",
      spl: "Sysmon EventCode=1 Image vssadmin.exe CommandLine delete OR wmic shadowcopy delete",
      cql: "ProcessRollup2 FileName vssadmin.exe CommandLine delete OR wmic shadowcopy",
    },
  },
  {
    id: "H024",
    title: "DLL Search Order Hijacking",
    hypothesis: "I hypothesize that an adversary has planted a malicious DLL in a location that will be loaded before the legitimate DLL, observable as unsigned DLLs loaded from user-writable paths by privileged processes.",
    tactic: "Persistence",
    techniqueId: "T1574.001",
    techniqueName: "DLL Search Order Hijacking",
    attackUrl: "https://attack.mitre.org/techniques/T1574/001/",
    priority: "HIGH",
    dataSources: ["Module Load Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "Unsigned DLLs loaded from temp or user directories by system processes",
      kql: "DeviceImageLoadEvents unsigned DLLs from non-system paths by privileged processes",
      spl: "Sysmon EventCode=7 Signed=false ImageLoaded from user-writable paths",
      cql: "ProcessRollup2 unsigned DLL loads from unexpected paths",
    },
  },
  {
    id: "H025",
    title: "Masquerading — Double Extension or Name Spoofing",
    hypothesis: "I hypothesize that an adversary is masquerading malware as legitimate files using double extensions or names mimicking system binaries, observable as executables with document-like names or running from unexpected paths.",
    tactic: "Defense Evasion",
    techniqueId: "T1036",
    techniqueName: "Masquerading",
    attackUrl: "https://attack.mitre.org/techniques/T1036/",
    priority: "HIGH",
    dataSources: ["Process Events", "File Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "Executables with .pdf.exe or .docx.exe double extensions or svchost.exe outside System32",
      kql: "DeviceProcessEvents FileName matches system binary names from non-system paths",
      spl: "Sysmon EventCode=1 double extension filenames or system binary names wrong path",
      cql: "ProcessRollup2 FileName double extension OR system binary name unexpected path",
    },
  },

  // ── DISCOVERY ─────────────────────────────────────────────────────────────────
  {
    id: "H026",
    title: "Active Directory Reconnaissance",
    hypothesis: "I hypothesize that an adversary is performing Active Directory enumeration to map the domain, observable as adfind.exe, ldapsearch, or unusual LDAP queries enumerating users, groups, and computers from workstations.",
    tactic: "Discovery",
    techniqueId: "T1018",
    techniqueName: "Remote System Discovery",
    attackUrl: "https://attack.mitre.org/techniques/T1018/",
    priority: "HIGH",
    dataSources: ["Process Events", "Directory Service Logs"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "adfind.exe execution or net.exe group domain admins queries from workstations",
      kql: "DeviceProcessEvents adfind.exe or net.exe with domain enumeration arguments",
      spl: "Sysmon EventCode=1 Image adfind.exe OR net.exe CommandLine domain group",
      cql: "ProcessRollup2 FileName adfind.exe OR net.exe CommandLine group domain",
    },
  },
  {
    id: "H027",
    title: "Network Port Scan from Internal Host",
    hypothesis: "I hypothesize that an adversary-controlled internal host is performing network reconnaissance via port scanning, observable as a single source IP making connection attempts to many destination hosts or ports in a short time window.",
    tactic: "Discovery",
    techniqueId: "T1046",
    techniqueName: "Network Service Discovery",
    attackUrl: "https://attack.mitre.org/techniques/T1046/",
    priority: "HIGH",
    dataSources: ["Network Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "Single host connecting to more than 50 unique internal IPs within 10 minutes",
      kql: "DeviceNetworkEvents single device connecting to many unique RemoteIPs",
      spl: "Network traffic single src_ip high count unique dest_ip short timeframe",
      cql: "NetworkConnectIP4 single ComputerName many unique RemoteAddressIP4",
    },
  },
  {
    id: "H028",
    title: "Domain Trust Discovery",
    hypothesis: "I hypothesize that an adversary is enumerating domain trusts to identify attack paths for lateral movement or privilege escalation, observable as nltest.exe domain trust queries or PowerShell Get-ADTrust commands.",
    tactic: "Discovery",
    techniqueId: "T1482",
    techniqueName: "Domain Trust Discovery",
    attackUrl: "https://attack.mitre.org/techniques/T1482/",
    priority: "MEDIUM",
    dataSources: ["Process Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "nltest.exe /domain_trusts or PowerShell Get-ADTrust from workstations",
      kql: "DeviceProcessEvents nltest.exe with domain_trusts or dclist arguments",
      spl: "Sysmon EventCode=1 Image nltest.exe CommandLine domain_trusts OR dclist",
      cql: "ProcessRollup2 FileName nltest.exe CommandLine domain_trusts",
    },
  },

  // ── COMMAND AND CONTROL ───────────────────────────────────────────────────────
  {
    id: "H029",
    title: "C2 Beaconing — High Frequency Outbound",
    hypothesis: "I hypothesize that a compromised host is communicating with a C2 server using regular beaconing, observable as a process making repeated outbound connections to the same external IP at consistent intervals.",
    tactic: "Command and Control",
    techniqueId: "T1071",
    techniqueName: "Application Layer Protocol",
    attackUrl: "https://attack.mitre.org/techniques/T1071/",
    priority: "CRITICAL",
    dataSources: ["Network Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "Processes with more than 100 outbound connections to same external IP, last 24 hours",
      kql: "DeviceNetworkEvents RemoteIPType Public grouped by device and RemoteIP count over 50",
      spl: "Network traffic external dest_ip grouped by src_ip dest_ip count over 100",
      cql: "NetworkConnectIP4 external RemoteAddressIP4 grouped by ComputerName count over 100",
    },
  },
  {
    id: "H030",
    title: "DNS Tunneling — Long or High-Volume DNS Queries",
    hypothesis: "I hypothesize that an adversary is exfiltrating data or communicating with C2 via DNS tunneling, observable as unusually long DNS query names, high query volume to a single domain, or queries for uncommon record types (TXT, NULL).",
    tactic: "Command and Control",
    techniqueId: "T1071.004",
    techniqueName: "DNS",
    attackUrl: "https://attack.mitre.org/techniques/T1071/004/",
    priority: "HIGH",
    dataSources: ["DNS Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "DNS queries longer than 50 characters or more than 100 queries to same domain",
      kql: "DnsEvents query length over 50 characters or high volume to single domain",
      spl: "DNS stream queries long query names or high volume single domain",
      cql: "DnsRequest DomainName length over 50 or high frequency single domain",
    },
  },
  {
    id: "H031",
    title: "Ingress Tool Transfer — Remote File Download",
    hypothesis: "I hypothesize that an adversary is downloading additional tools or payloads using built-in utilities, observable as curl, wget, certutil, or PowerShell downloading executables or scripts to temp directories.",
    tactic: "Command and Control",
    techniqueId: "T1105",
    techniqueName: "Ingress Tool Transfer",
    attackUrl: "https://attack.mitre.org/techniques/T1105/",
    priority: "HIGH",
    dataSources: ["Process Events", "Network Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "curl, wget, certutil, or PowerShell downloading files to temp or user directories",
      kql: "DeviceProcessEvents download commands with output to temp paths",
      spl: "Sysmon EventCode=1 download utilities with outfile or output to temp",
      cql: "ProcessRollup2 FileName curl OR wget OR certutil CommandLine download output",
    },
  },
  {
    id: "H032",
    title: "Non-Standard Port Communication",
    hypothesis: "I hypothesize that malware is communicating on non-standard ports to evade firewall rules, observable as common applications (browsers, Office) making outbound connections on unusual ports like 4444, 8443, or 1337.",
    tactic: "Command and Control",
    techniqueId: "T1571",
    techniqueName: "Non-Standard Port",
    attackUrl: "https://attack.mitre.org/techniques/T1571/",
    priority: "MEDIUM",
    dataSources: ["Network Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "Office or browser processes making connections on ports other than 80, 443, 8080",
      kql: "DeviceNetworkEvents Office apps connecting on non-standard ports",
      spl: "Network traffic Office app src_process unusual dest_port",
      cql: "NetworkConnectIP4 Office application FileName unusual RemotePort",
    },
  },

  // ── EXFILTRATION ──────────────────────────────────────────────────────────────
  {
    id: "H033",
    title: "Data Exfiltration to Cloud Storage",
    hypothesis: "I hypothesize that an adversary is exfiltrating data by uploading to cloud storage services (rclone, S3, OneDrive abuse), observable as rclone.exe or unusual upload volumes to cloud storage endpoints outside business hours.",
    tactic: "Exfiltration",
    techniqueId: "T1567.002",
    techniqueName: "Exfiltration to Cloud Storage",
    attackUrl: "https://attack.mitre.org/techniques/T1567/002/",
    priority: "HIGH",
    dataSources: ["Process Events", "Network Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "rclone.exe execution or large outbound transfers to cloud storage IPs outside business hours",
      kql: "DeviceProcessEvents rclone.exe or large DeviceNetworkEvents to cloud storage",
      spl: "Sysmon EventCode=1 Image rclone.exe OR network large bytes cloud storage endpoints",
      cql: "ProcessRollup2 FileName rclone.exe OR NetworkConnectIP4 large transfer cloud",
    },
  },
  {
    id: "H034",
    title: "Large Outbound Data Transfer",
    hypothesis: "I hypothesize that an adversary is staging and exfiltrating large volumes of data, observable as a single host transferring unusually large amounts of data to an external destination over a short time period.",
    tactic: "Exfiltration",
    techniqueId: "T1041",
    techniqueName: "Exfiltration Over C2 Channel",
    attackUrl: "https://attack.mitre.org/techniques/T1041/",
    priority: "HIGH",
    dataSources: ["Network Events"],
    falsePositiveRisk: "HIGH",
    queryHints: {
      xql: "Hosts with outbound bytes over 500MB to external IPs in last 24 hours",
      kql: "DeviceNetworkEvents sum bytes sent to RemoteIPType Public over threshold",
      spl: "Network traffic external dest sum bytes_out by src_ip over 500MB",
      cql: "NetworkConnectIP4 external destinations high total bytes by ComputerName",
    },
  },

  // ── IMPACT ────────────────────────────────────────────────────────────────────
  {
    id: "H035",
    title: "Mass File Encryption — Ransomware",
    hypothesis: "I hypothesize that ransomware is actively encrypting files on a host, observable as a single process creating or modifying an unusually large number of files with new or changed extensions in a short time period.",
    tactic: "Impact",
    techniqueId: "T1486",
    techniqueName: "Data Encrypted for Impact",
    attackUrl: "https://attack.mitre.org/techniques/T1486/",
    priority: "CRITICAL",
    dataSources: ["File Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "Single process modifying more than 100 files in under 5 minutes with new extensions",
      kql: "DeviceFileEvents single process high file modification count unusual extensions",
      spl: "Sysmon EventCode=11 high count file creates single process short timeframe",
      cql: "NewExecutableWritten or file modification events high count single process",
    },
  },
  {
    id: "H036",
    title: "Backup Deletion — Pre-Ransomware",
    hypothesis: "I hypothesize that an adversary is preparing for a destructive attack by deleting backups, observable as wbadmin delete, bcdedit boot recovery changes, or vssadmin resize commands alongside shadow copy deletion.",
    tactic: "Impact",
    techniqueId: "T1490",
    techniqueName: "Inhibit System Recovery",
    attackUrl: "https://attack.mitre.org/techniques/T1490/",
    priority: "CRITICAL",
    dataSources: ["Process Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "wbadmin delete backup or bcdedit recoveryenabled no commands",
      kql: "DeviceProcessEvents wbadmin.exe or bcdedit.exe with recovery disable flags",
      spl: "Sysmon EventCode=1 Image wbadmin.exe OR bcdedit.exe CommandLine delete OR no",
      cql: "ProcessRollup2 FileName wbadmin.exe OR bcdedit.exe CommandLine delete",
    },
  },

  // ── INITIAL ACCESS ────────────────────────────────────────────────────────────
  {
    id: "H037",
    title: "Password Spray Attack",
    hypothesis: "I hypothesize that an adversary is performing a password spray attack against corporate accounts, observable as a single source IP attempting authentication against many different usernames with the same password in a short window.",
    tactic: "Credential Access",
    techniqueId: "T1110.003",
    techniqueName: "Password Spraying",
    attackUrl: "https://attack.mitre.org/techniques/T1110/003/",
    priority: "CRITICAL",
    dataSources: ["Authentication Events"],
    falsePositiveRisk: "LOW",
    queryHints: {
      xql: "Single source IP with failed auth attempts against many different usernames in one hour",
      kql: "SigninLogs many distinct UserPrincipalName failures from single IP",
      spl: "EventCode=4625 single IpAddress many distinct TargetUserName failures",
      cql: "UserLogon failed many distinct UserName from single aip",
    },
  },
  {
    id: "H038",
    title: "Impossible Travel — Concurrent Logins",
    hypothesis: "I hypothesize that account credentials have been compromised and are being used from multiple geographic locations simultaneously, observable as the same user authenticating from geographically distant IPs within an impossibly short timeframe.",
    tactic: "Initial Access",
    techniqueId: "T1078",
    techniqueName: "Valid Accounts",
    attackUrl: "https://attack.mitre.org/techniques/T1078/",
    priority: "CRITICAL",
    dataSources: ["Authentication Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "Same user with successful logins from different countries within 1 hour",
      kql: "SigninLogs same UserPrincipalName from multiple distinct countries same hour",
      spl: "auth events same user multiple distinct country codes within 1 hour",
      cql: "UserLogon same UserName from multiple distinct geographic locations",
    },
  },
  {
    id: "H039",
    title: "New Admin Account Creation",
    hypothesis: "I hypothesize that an adversary created a new privileged account for persistence, observable as net.exe or PowerShell creating new user accounts and adding them to Domain Admins or local Administrators outside of approved provisioning.",
    tactic: "Persistence",
    techniqueId: "T1136.001",
    techniqueName: "Local Account",
    attackUrl: "https://attack.mitre.org/techniques/T1136/001/",
    priority: "CRITICAL",
    dataSources: ["Process Events", "Security Events"],
    falsePositiveRisk: "MEDIUM",
    queryHints: {
      xql: "net.exe user /add or net.exe localgroup administrators /add commands",
      kql: "DeviceProcessEvents net.exe user add or SecurityEvent EventID 4720 4732",
      spl: "EventCode=4720 new account created OR EventCode=4732 added to admins group",
      cql: "ProcessRollup2 FileName net.exe CommandLine user /add OR localgroup admin",
    },
  },
  {
    id: "H040",
    title: "Suspicious Logon Outside Business Hours",
    hypothesis: "I hypothesize that compromised credentials are being used by an adversary outside of normal working hours, observable as interactive logons to sensitive systems occurring between midnight and 6am local time from unexpected accounts.",
    tactic: "Initial Access",
    techniqueId: "T1078",
    techniqueName: "Valid Accounts",
    attackUrl: "https://attack.mitre.org/techniques/T1078/",
    priority: "MEDIUM",
    dataSources: ["Authentication Events"],
    falsePositiveRisk: "HIGH",
    queryHints: {
      xql: "Interactive logons to servers between midnight and 6am from non-service accounts",
      kql: "DeviceLogonEvents interactive logons on servers outside 6am-10pm window",
      spl: "EventCode=4624 LogonType=2 OR LogonType=10 outside business hours servers",
      cql: "UserLogon interactive LogonType servers outside business hours",
    },
  },
];

export function getHypothesisByTactic(tactic: string): HuntHypothesis[] {
  return HUNT_HYPOTHESES.filter((h) => h.tactic === tactic);
}

export function getHypothesisByPriority(priority: "CRITICAL" | "HIGH" | "MEDIUM"): HuntHypothesis[] {
  return HUNT_HYPOTHESES.filter((h) => h.priority === priority);
}

export const TACTICS = Array.from(new Set(HUNT_HYPOTHESES.map((h) => h.tactic)));
